# Generated by Django 5.2.3 on 2025-06-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='store/images/dress.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
